### ISSUE TITLE
Error from MC-Index?

### ISSUE THREAD

**Issue by DeadIntermediate** [NuVotifier/NuVotifier#117]
I got this error when I voted on MC-Index. Not sure if I should be concerned or not.

`
10:40:03 [SEVERE] [NuVotifier] Unable to process vote from /146.0.77.29:407
java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
    at com.vexsoftware.votifier.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
    at com.vexsoftware.votifier.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
    at com.vexsoftware.votifier.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)
    at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
    at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
    at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
    at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
    at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
    at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
`

**Comment by Ichbinjoe** [comment]
Try the latest dev build: https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar

Connection reset by peer is caused by the remote side 'hanging up' the TCP connection before we get a chance to process the vote. This is an error in the sites handling, but we can attempt to handle it with better handling from our side if I could find the flag...

**Comment by jammer131** [comment]
i am having the same problem but not from mc-index. mine is from minecraft-mp

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/blob/master/docs/faq.md#connection-reset-by-peer
