### ISSUE TITLE
Plugin error after recieving vote

### ISSUE THREAD

**Issue by SharkROAR** [NuVotifier/NuVotifier#12]
Recieving this error:

`[07:22:11] [pool-2-thread-4/ERROR] [Sponge]: The Scheduler tried to run the task nuvotifier-A-151 owned by org.spongepowered.mod.plugin.SpongeModPluginContainer@1164f983, but an error occured.
java.lang.NoSuchMethodError: org.spongepowered.api.event.cause.Cause.of(Ljava/lang/Object;[Ljava/lang/Object;)Lorg/spongepowered/api/event/cause/Cause;
        at com.vexsoftware.votifier.sponge.VotifierPlugin$3.run(VotifierPlugin.java:354) ~[VotifierPlugin$3.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.8.9-1890-4.2.0-BETA-1574]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.8.9-1890-4.2.0-BETA-1574]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
`

Using:
`Minecraft: 1.8.9
    SpongeAPI: 4.2.0-SNAPSHOT-c988e70
    SpongeForge: 1.8.9-1890-4.2.0-BETA-1574
    Minecraft Forge: 11.15.1.1890
`

**Comment by Ichbinjoe** [comment]
Votifier is only compiled against 4.1.0 stable API.
