### ISSUE TITLE
Task #7351 for Votifier v2.5.1 generated an exception

### ISSUE THREAD

**Issue by RedbearPlayz** [NuVotifier/NuVotifier#133]
Im Trying to add a voting system to the server but this keeps happening. ive tried checking the pub.key and changing the port, nothing is working.
```
05.05 16:11:08 [Server] WARN Task #7351 for Votifier v2.5.1 generated an exception
05.05 16:11:08 [Server] INFO java.lang.LinkageError: loader constraint violation: when resolving method "com.vexsoftware.votifier.model.VotifierEvent.<init>(Lcom/vexsoftware/votifier/model/Vote;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/vexsoftware/votifier/NuVotifierBukkit, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/vexsoftware/votifier/model/VotifierEvent, have different Class objects for the type com/vexsoftware/votifier/model/Vote used in the signature
05.05 16:11:08 [Server] INFO at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:368) ~[?:?]
05.05 16:11:08 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot_Latest_1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
05.05 16:11:08 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [Spigot_Latest_1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
05.05 16:11:08 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [Spigot_Latest_1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
05.05 16:11:08 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot_Latest_1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
05.05 16:11:08 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [Spigot_Latest_1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
05.05 16:11:08 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [Spigot_Latest_1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
05.05 16:11:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by Ichbinjoe** [comment]
Do not use /reload or /plugman with NuVotifier. It does not support it, nor will it ever. Restart your server.

**Comment by RedbearPlayz** [comment]
That fixed it thanks!
