### ISSUE TITLE
Exception purging votes

### ISSUE THREAD

**Issue by Artuto** [NuVotifier/NuVotifier#139]
I got these logs today in my Bungee console:

``` 
> [18:16:33 WARN] [NuVotifier]: Purging out of date vote.
> [18:16:33 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@60e949e1, id=55, owner=com.vexsoftware.votifier.bungee.NuVotifier@5939e24, task=com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache$$Lambda$198/1608357825@3b5a19ed, delay=180000, period=180000, running=true) encountered an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.remove(HashMap.java:1459) ~[?:1.8.0_212]
at com.vexsoftware.votifier.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.remove(AbstractMapBasedMultimap.java:1431) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.serializeMap(FileVoteCache.java:153) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.save(FileVoteCache.java:120) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.lambda$new$0(FileVoteCache.java:33) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> [18:19:33 WARN] [NuVotifier]: Purging out of date vote.
> [18:19:33 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@60e949e1, id=55, owner=com.vexsoftware.votifier.bungee.NuVotifier@5939e24, task=com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache$$Lambda$198/1608357825@3b5a19ed, delay=180000, period=180000, running=true) encountered an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.remove(HashMap.java:1459) ~[?:1.8.0_212]
at com.vexsoftware.votifier.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.remove(AbstractMapBasedMultimap.java:1431) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.serializeMap(FileVoteCache.java:153) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.save(FileVoteCache.java:120) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.lambda$new$0(FileVoteCache.java:33) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> [18:22:33 WARN] [NuVotifier]: Purging out of date vote.
> [18:22:33 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@60e949e1, id=55, owner=com.vexsoftware.votifier.bungee.NuVotifier@5939e24, task=com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache$$Lambda$198/1608357825@3b5a19ed, delay=180000, period=180000, running=true) encountered an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.remove(HashMap.java:1459) ~[?:1.8.0_212]
at com.vexsoftware.votifier.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.remove(AbstractMapBasedMultimap.java:1431) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.serializeMap(FileVoteCache.java:153) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.save(FileVoteCache.java:120) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.lambda$new$0(FileVoteCache.java:33) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```

**Comment by eightbitx** [comment]
I have this same error.

Log: https://pastebin.com/hLkt7Nex
Config: https://pastebin.com/77pFtJR3
Version: 2.5.2
Waterfall version: git:Waterfall-Bootstrap:1.14-SNAPSHOT:2afc278:283 by md_5 (build # 283 for 1.14.1)
