### ISSUE TITLE
Error on startup with newest Java update

### ISSUE THREAD

**Issue by TrollyLoki** [NuVotifier/NuVotifier#151]
I recently updated to the newest version of Java 8 (Java 8 Update 221) and when loading my BungeeCord proxy this happened:
``[INFO] [NuVotifier] Loaded token for website: default
[INFO] [NuVotifier] Votifier enabled on socket /0:0:0:0:0:0:0:0:25569.
[WARNING] Exception encountered when loading plugin: NuVotifier
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.load(FileVoteCache.java:52)
	at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.<init>(FileVoteCache.java:29)
	at com.vexsoftware.votifier.bungee.NuVotifier.loadAndBind(NuVotifier.java:231)
	at com.vexsoftware.votifier.bungee.NuVotifier.onEnable(NuVotifier.java:299)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)``

**Comment by Ichbinjoe** [comment]
Looks like a corrupt file cache. Delete and restart.

**Comment by TrollyLoki** [comment]
Yup, I opened the cache file and it was just a bunch of nulls. No idea how that happened. Thanks for the help
