### ISSUE TITLE
BungeeCord and Spigot not working as Expected at 1.14.4

### ISSUE THREAD

**Issue by XaviFortes** [NuVotifier/NuVotifier#154]
I was using the plugin in Spigot only and testing when I realized a test vote nothing happened, so I looked deeper in the Spigot page and I found I can use it in BungeeCoord so I installed the plugin, set up the proxy, etc. And I got this error
```

Caused by: javax.crypto.BadPaddingException: Decryption error
    at java.base/sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:378)
    at java.base/sun.security.rsa.RSAPadding.unpad(RSAPadding.java:290)
    at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:366)
    at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:392)
    at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
    at com.vexsoftware.votifier.net.protocol.v1crypto.RSA.decrypt(RSA.java:58)
    at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:32)
    ... 28 more
```
I've got more than this error, just to let you know by what is caused, I'm in JDK 11

**Comment by Ichbinjoe** [comment]
You did not send the full error.

Looks like the wrong key was pasted into the test site.
