### ISSUE TITLE
Getting Exeption sometimes

### ISSUE THREAD

**Issue by BloodSKreaper** [NuVotifier/NuVotifier#163]
I receive the following error in the console sometimes. I do not really know what the source of the vote connection is but it surely shouldn´t trigger an error.

Here´s the error code:
`
[15:43:33] [Votifier NIO worker/ERROR]: [Votifier] Unable to process vote from /5.101.64.77:64738
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[?:?]
	at com.vexsoftware.votifier.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[nuvotifier-2.5.3.jar:?]
	at com.vexsoftware.votifier.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[nuvotifier-2.5.3.jar:?]
	at com.vexsoftware.votifier.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[nuvotifier-2.5.3.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) [nuvotifier-2.5.3.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [nuvotifier-2.5.3.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) [nuvotifier-2.5.3.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) [nuvotifier-2.5.3.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [nuvotifier-2.5.3.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [nuvotifier-2.5.3.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#connection-reset-by-peer
