### ISSUE TITLE
Unable to process utf-8 unicode characters

### ISSUE THREAD

**Issue by weihao** [NuVotifier/NuVotifier#174]
Node POST:
```
  vote: {
    username: '你好世界',
    address: '127.0.0.1',
    timestamp: 1582274645424,
    serviceName: 'Test'
  }
```

Java backend:
[03:44:05] [Votifier NIO worker/ERROR]: [Votifier] Unable to process vote from /192.168.1.1:64218
com.vexsoftware.votifier.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 217 path $.signature
        at com.vexsoftware.votifier.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [nuvotifier-3.0.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 217 path $.signature
        at com.google.gson.Gson.fromJson(Gson.java:947) ~[serverjars-1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[serverjars-1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[serverjars-1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:817) ~[serverjars-1.jar:?]
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol2Decoder.decode(VotifierProtocol2Decoder.java:29) ~[?:?]
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol2Decoder.decode(VotifierProtocol2Decoder.java:23) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[?:?]
        ... 34 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 217 path $.signature
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564) ~[serverjars-1.jar:?]
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1032) ~[serverjars-1.jar:?]
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:816) ~[serverjars-1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702) ~[serverjars-1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723) ~[serverjars-1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698) ~[serverjars-1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:894) ~[serverjars-1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[serverjars-1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[serverjars-1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[serverjars-1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:817) ~[serverjars-1.jar:?]
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol2Decoder.decode(VotifierProtocol2Decoder.java:29) ~[?:?]
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol2Decoder.decode(VotifierProtocol2Decoder.java:23) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[?:?]
        ... 34 more
>

**Comment by Ichbinjoe** [comment]
That's an invalid username. Why would NuVotifier support that?

https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames

**Comment by weihao** [comment]
Considering:
1. Custom plugins may allow players to include special characters in the user nick.

2. Add internationalization support for non-English speaking countries. For example, `Minecraft has almost 300 million registered accounts in China`, but those registered accounts do not follow Mojang's schema. So it is generally a good idea to add support for utf8. I think the [bstats](https://bstats.org/plugin/bukkit/VotingPlugin/38) metrics are self-explanatory.

**Comment by Ichbinjoe** [comment]
1. The field in question here is not the user nick (or shouldn't be. a plugin making a change to this field will break many other plugins assumptions about this field). It is the raw username of the player.

2. I18n support hasn't been added in the past since it has never been needed - NuVotifier is not a 'user' facing plugin (i.e. no messages sent to the players on the server). Simple ASCII support has been fine for all other non-english speaking countries because the username is _always_ constrained to the username rules above. I cannot find any documentation specifying rules for username creation in Minecraft China (probably because I do not speak Chinese). Could you please share some?

I will also be more than happy to accept a PR fixing this :)

**Comment by weihao** [comment]
I think username creation has the same requirement for length, but it supports utf-8 characters.

I found an issue that when passing those characters in a post request to votifier, LengthFieldBasedFrameDecoder failed to receive the full encoded json message and cuts off the last few characters. I thought it was a maxFrameLength issue, but apparently it wasn't after a few tests.

**Comment by weihao** [comment]
Solved.
