### ISSUE TITLE
Port bug when server stop 1.8.8 spigot

### ISSUE THREAD

**Issue by Flayovec** [NuVotifier/NuVotifier#19]
Hello, good plugin but sometime I have problems...

[19:46:13] [nioEventLoopGroup-2-1/WARN]: Failed to fail the promise because its done already: DefaultChannelPromise@678b1254(success) 
java.util.ConcurrentModificationException 
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711) ~[?:1.8.0_45] 
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734) ~[?:1.8.0_45] 
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45] 
at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.deregister(AbstractChannel.java:656) ~[nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.fireChannelInactiveAndDeregister(AbstractChannel.java:626) ~[nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:600) ~[nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1107) ~[nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:543) [nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:32) [nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:533) [nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) [nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [nuvotifier-universal-2.3.3.jar:?] 
at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [nuvotifier-universal-2.3.3.jar:?] 
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45] 

And this cause problem with my server, NuVotifier use port of my server but I have in config specificed port 29112 and server has 26112...

Please fix it !

PS: Sorry for my bad english

**Comment by Ichbinjoe** [comment]
Possibly fixed in 2.3.6

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/releases/tag/v2.3.6-pre

Please try this version. Reopen this issue if you are still having issues.
