### ISSUE TITLE
Stacktrace when reloading on Paper

### ISSUE THREAD

**Issue by StealWonders** [NuVotifier/NuVotifier#191]
### Information

**Platform on which you run NuVotifier**: Bukkit

**Version of NuVotifier**: 3.0.0-SNAPSHOT

### Details

**Description**  
Stacktrace: 
`[15:45:42 ERROR]: [com.vexsoftware.votifier.netty.util.concurrent.DefaultPromise.rejectedExecution] Failed to submit a listener notification task. Event loop shut down?
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_242]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_242]
        at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_242]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.15.2.jar:git-Paper-327]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.15.2.jar:git-Paper-327]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Paper-327]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-327]
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953) ~[?:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:898) ~[?:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:881) ~[?:1.8.0_242]
        at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory.newThread(DefaultThreadFactory.java:108) ~[?:?]
        at com.vexsoftware.votifier.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:219) ~[?:?]
        at com.vexsoftware.votifier.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:213) ~[?:?]
        at com.vexsoftware.votifier.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) ~[?:?]
        at com.vexsoftware.votifier.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) ~[?:?]
        at com.vexsoftware.votifier.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94) ~[?:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:951) ~[?:?]
        at java.lang.Thread.run(Thread.java:821) [?:1.8.0_242]`

**Steps to reproduce**  
When I use `/rl confirm` the following stack trace gets printed to the console.

I am listening for vote events using the following code:

`
public class VoteListener implements Listener {

    @EventHandler
    public void onVote(VotifierEvent event) {
        Vote vote = event.getVote();
        //todo: whatever
    }
}
`

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#i-used-reload-or-plugman-on-nuvotifier-and-now-it-doesnt-work

`/reload` is fundamentally broken anyway
