### ISSUE TITLE
>.... [17:31:32 ERROR] [NuVotifier]: Unable to process vote from IP:PORT

### ISSUE THREAD

**Issue by speex1** [NuVotifier/NuVotifier#200]
om.vexsoftware.votifier.io.netty.handler.codec.CorruptedFrameException: Could not decrypt data from IP:PORT Make sure the public key on the list is correct.
at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:46) ~[?:?]
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[?:?]
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[?:?]
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[?:?]
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[?:?]
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[?:?]
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[?:?]
at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[?:?]
at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: javax.crypto.BadPaddingException: Message is larger than modulus
at sun.security.rsa.RSACore.parseMsg(RSACore.java:214) ~[?:1.8.0_242]
at sun.security.rsa.RSACore.crtCrypt(RSACore.java:166) ~[?:1.8.0_242]
at sun.security.rsa.RSACore.rsa(RSACore.java:122) ~[?:1.8.0_242]
at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:362) ~[sunjce_provider.jar:1.8.0_242]
at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_242]
at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_242]
at com.vexsoftware.votifier.net.protocol.v1crypto.RSA.decrypt(RSA.java:58) ~[?:?]
at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:43) ~[?:?]
... 24 more

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide
