### ISSUE TITLE
public key wont change!

### ISSUE THREAD

**Issue by Krazytrain** [NuVotifier/NuVotifier#212]
Im trying to get votifier to change the public key and it wont, iv removed all files and re uploaded the plugin on all servers and bungee and its keep bringing back the old configs. 
Im using the upto date unvotifier as iv just updated it today. Its a paper bungee server and iv made sure all servers have there own ports and they are forwarded. 

Consoles gives me this- 

com.vexsoftware.votifier.io.netty.handler.codec.CorruptedFrameException: Could not decrypt data from /50.28.37.175:60424. Make sure the public key on the list is correct.
at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:46)
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at com.vexsoftware.votifier.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
Caused by: javax.crypto.BadPaddingException: Decryption error
at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:379)
at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:290)
at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:365)
at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:391)
at javax.crypto.Cipher.doFinal(Cipher.java:2168)
at com.vexsoftware.votifier.net.protocol.v1crypto.RSA.decrypt(RSA.java:58)
at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:43)

**Comment by Krazytrain** [comment]
Why would you close this when iv tried to reset the public key so it will work? Iv tried wiping all the files for the plugin and re uploaded the updated one and still bring back the old data

**Comment by astei** [comment]
[This is explained on the Spigot resource page](https://www.spigotmc.org/resources/nuvotifier.13449/). We do not provide support setup any more.

**Comment by Krazytrain** [comment]
ok but if i removed all the files and re added the plugin and its not making the default files just keeps bring back the old ones iv asked others and they said its a bug because it should create the default files

**Comment by Krazytrain** [comment]
The console is saying the public key is wrong which is not its the one in our bungee folder. Iv tried everything to reset the configs even tried using an older version of the plugin

**Comment by astei** [comment]
You are doing something wrong. Please make sure to use the key for the proxy and that the vote site points to your proxy server.

**Comment by Krazytrain** [comment]
i did i set the vote sites for the bungee server with ip and port, Do you need to port forward all the servers ports or just the one for the bungee? As right now we have them all to port forward and its not working.

**Comment by Krazytrain** [comment]
Iv set bungee to the vote sites and in the bungee config iv set each server with ports and ips they are different ports from each other and all forwarded out. Iv set each key too in the bungee config. Is there something im missing? The only thing console is saying is it is the wrong public key which iv tried to change it by wiping the files and re starting the servers but its not making a new public key just the old one.
