### ISSUE TITLE
Exception in thread "Votifier NIO worker" kava.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by mrfloris** [NuVotifier/NuVotifier#241]
This is a first for me, I've been using NuVotifier forever and today on running `stop` from console I noticed an error and it showed this. 
```
[16:08:09 INFO]: [Votifier] Disabling Votifier v2.7.2
[16:08:09 INFO]: [Votifier] Votifier disabled.
[16:08:09 WARN]: Exception in thread "Votifier NIO worker" Exception in thread "Votifier NIO worker" java.lang.IllegalStateException: zip file closed
[16:08:09 WARN]: Exception in thread "Votifier NIO worker"      at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:08:09 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:08:09 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:08:09 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165)
[16:08:09 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[16:08:09 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolArena.freeChunk(PoolArena.java:298)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:465)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:431)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:423)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:277)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:268)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:239)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:491)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:458)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:256)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1042)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:08:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[16:08:09 WARN]: java.lang.IllegalStateException: zip file closed
[16:08:09 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:08:09 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:08:09 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:08:09 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165)
[16:08:09 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[16:08:09 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolArena.freeChunk(PoolArena.java:298)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:465)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:431)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:423)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:277)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:268)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:239)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:491)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:458)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:256)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1042)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:08:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[16:08:09 WARN]: java.lang.IllegalStateException: zip file closed
[16:08:09 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:08:09 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:08:09 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:08:09 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165)
[16:08:09 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[16:08:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[16:08:09 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolArena.freeChunk(PoolArena.java:298)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:465)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:431)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:423)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:277)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:268)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:239)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:491)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:458)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:256)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1042)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:08:09 WARN]:        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:08:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

```
> ver Votifier
[16:10:04 INFO]: Votifier version 2.7.2
[16:10:04 INFO]: A plugin that gets notified when votes are made for the server on toplists.
[16:10:04 INFO]: Authors: Ichbinjoe, blakeman8192, Kramer and tuxed
> ver
[16:10:05 INFO]: Checking version, please wait...
[16:10:05 INFO]: This server is running Paper version git-Paper-678 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 5 version(s) behind
Previous version: git-Paper-680 (MC: 1.16.5)
>

java 16
```

**Comment by Ichbinjoe** [comment]
So this is likely harmless to your server, but does indicate that NuVotifier may not be cleanly cleaning up threads (thus, the thread keeps on going, tries to free something, everything breaks because server has already cleaned stuff up).

Maybe, that or you changed the jar out from under NuVotifier which is the more common cause of this break.

**Comment by mrfloris** [comment]
> So this is likely harmless to your server, but does indicate that NuVotifier may not be cleanly cleaning up threads (thus, the thread keeps on going, tries to free something, everything breaks because server has already cleaned stuff up).
> 
> Maybe, that or you changed the jar out from under NuVotifier which is the more common cause of this break.

Same jar as we had in a while. The server was idle for 15+ minutes, and it was a regular stop from console. 

I will go check the nvme ssd to see if there's any io issues, etc. 

Thank you for the additional information. I will go to ci and get a jar again and keep an eye on it.

**Comment by mibby** [comment]
I'm also able to confirm this existing in my environment with a Paper 1.16.5 fork & nuVotifier dev 86. 

```
[00:47:35] [Votifier epoll worker/WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:934) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:361) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1140) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:166) ~[patched_1.16.5.jar"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:120) ~[patched_1.16.5.jar"]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[00:47:35] [Votifier epoll boss/WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:934) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:361) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1140) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:166) ~[patched_1.16.5.jar"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:120) ~[patched_1.16.5.jar"]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[00:47:35] [Votifier epoll worker/WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:934) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:361) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1140) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:166) ~[patched_1.16.5.jar"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:120) ~[patched_1.16.5.jar"]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[00:47:35] [Votifier epoll worker/WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:934) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:361) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1140) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:166) ~[patched_1.16.5.jar"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:120) ~[patched_1.16.5.jar"]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by CloudeLecaw** [comment]
I can agree this Happens at out server too when the server stops or restartes.

**Comment by mrfloris** [comment]
Handful of people on spigot are reporting it too now. Glad to see it's not just me. Oof, best of luck figuring out what bukkit/spigot or paper has changed that caused this.

**Comment by Baktus79** [comment]
Same problem here!

PaperMC 1.16.5 Build 711
NuVotifier Version: 2.7.2
Java 11

**Comment by KolakZ** [comment]
Same issue here when Tuinity updated Paper upstream!

Tuinity Build #231
NuVotifier Version 2.7.2
Java 16

**Comment by KolakZ** [comment]
I'm having the same issue!

Tuinity Build #231
NuVotifier Version 2.7.2
Java 16

**Comment by astei** [comment]
Posting comments to the effect of "me too" is profoundly unconstructive. Stop it.

**Comment by Baktus79** [comment]
> Posting comments to the effect of "me too" is profoundly unconstructive. Stop it.

Is it not constructive to know that more people are struggling with the same problem?

**Comment by astei** [comment]
It's constructive to know people are having the issue, but if you little more to add than "I have this issue too" then it doesn't help anyone.

**Comment by KolakZ** [comment]
Agree to disagree, if more people are having the same issue, it could get marked as a higher priority bug.

**Comment by Baktus79** [comment]
So what I should have done is to copy and paste the exact error message that is already shown? I brought version numbers on the table, that should have been of some help.

**Comment by astei** [comment]
You still didn't have anything else to add. Your addition of version numbers was completely useless since the OP already gave version numbers and your servers were clearly newer than that particular version of Paper. It was merely superfluous information. (If, however, a newer version of the server _fixed_ the issue, that's a different story).

This was an issue that could be safely ignored - it only shows up on shutdown (and in that case we want everything to go away anyway, so it's effectively harmless anyway) or on a classloader-based reload (which we've _never_ supported). It is the _very definition_ of "low priority".

Either way, the issue is fixed. I'm locking this issue, we're not going to argue over tiny minutiae.
