### ISSUE TITLE
Consoleerror on Serverrestart

### ISSUE THREAD

**Issue by CloudeLecaw** [NuVotifier/NuVotifier#243]
We have this error each day in the console when our server restarts

```
[06:00:20] [Server thread/INFO]: [Votifier] Disabling Votifier v3.0.0-SNAPSHOT
[06:00:20] [Server thread/INFO]: [Votifier] Votifier disabled.
[06:00:20] [Votifier epoll worker/WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-705]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-705]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-705]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[06:00:20] [Votifier epoll boss/WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-705]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-705]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-705]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[06:00:20] [Votifier epoll worker/WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-705]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-705]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-705]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[06:00:20] [Votifier epoll worker/WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-705]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-705]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-705]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
	at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Ichbinjoe** [comment]
#241

**Comment by astei** [comment]
Possibly corrupt JAR, not our issue.
