### ISSUE TITLE
Failed to submit a listener notification task. Event loop shut down?

### ISSUE THREAD

**Issue by mrfloris** [NuVotifier/NuVotifier#247]
```
[20:58:09 INFO]: [Votifier] Disabling Votifier v3.0.0-SNAPSHOT
[20:58:11 INFO]: [Votifier] Votifier disabled.
[20:58:11 ERROR]: [com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.rejectedExecution] Failed to submit a listener notification task. Event loop shut down?
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-715]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-715]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-715]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:220) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:208) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
```
> ver Votifier
[21:09:16 INFO]: Votifier version 3.0.0-SNAPSHOT
[21:09:16 INFO]: A plugin that gets notified when votes are made for the server on toplists.
[21:09:16 INFO]: Authors: Ichbinjoe, blakeman8192, Kramer and tuxed
> ver
[21:09:17 INFO]: This server is running Paper version git-Paper-720 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-715 (MC: 1.16.5)
>
```
The zip nio issue from the other day got closed, but had a follow up. 

Did /stop, and Updated nuvotifier from ci to try and fix the zip error I reported (issue ticket got closed, so can't follow up), added latest paper, and started the server. I did a /stop again and it's a different (but alike) error. I thought I'd follow up on it.

**Comment by KolakZ** [comment]
NuVotifier said they fixed it but they didn't...

**Comment by KolakZ** [comment]
It is safe to ignore though.

**Comment by astei** [comment]
Can't fix this. I've done all I can on the NuVotifier side to fix the issue without radical changes. The only way to remove this error is to remove Netty entirely, and not only is that project that doesn't interest me, it is also over an issue that has essentially zero impact on server operation.

**Comment by mrfloris** [comment]
Question, why would this suddenly become a thing when the OS etc isn't updated? We only updated a Paper build and suddenly it's a thing
