### ISSUE TITLE
Votes Not Working

### ISSUE THREAD

**Issue by KolakZ** [NuVotifier/NuVotifier#249]
This issue has been known for some time now and the contributors have stated that it is safe to ignore but it is not because this issue is making it so votes aren't processing correctly.

[22:25:05 ERROR] [NuVotifier]: Unable to process vote from /135.148.6.65:39044
com.vexsoftware.votifier.io.netty.handler.codec.CorruptedFrameException: Signature is not valid (invalid token?)
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol2Decoder.decode(VotifierProtocol2Decoder.java:56) ~[?:?]
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol2Decoder.decode(VotifierProtocol2Decoder.java:23) ~[?:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[?:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[?:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[?:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[?:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide
