### ISSUE TITLE
Error on stop

### ISSUE THREAD

**Issue by DevJoey** [NuVotifier/NuVotifier#254]
### Information

**Platform on which you run NuVotifier**: 

**Version of NuVotifier**: 
2.7.2

**Relevant log**: 
### Details

**Description**  
If i install nuvotifier on my spigot and stop it this exception is thrown
```
at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[17:19:13 WARN]: [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:915) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
        at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1121) ~[?:?]
        at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-759]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-759]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-759]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]
        at java.util.AbstractCollection.toArray(AbstractCollection.java:184) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
        at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
**Steps to reproduce**  
Install Java11 install a paper 1.16.5 server with newest paper install nuvotifier start and stop

**Expected behavior**  
No error on shutdown

**Comment by astei** [comment]
#247
