### ISSUE TITLE
NuVotifier Console Error - PaperSpigot 1.17

### ISSUE THREAD

**Issue by Waterman1001** [NuVotifier/NuVotifier#262]
### Information

**Platform on which you run NuVotifier**: 
Paper Spigot 1.17 build 66
**Version of NuVotifier**: 
2.7.2, this is the latest stable one.

**Relevant log**: https://gist.github.com/Waterman1001/88a668fc3db4a03f0085f5cf888df861

```bash
30.06 11:35:32 [Server] INFO [Votifier] Disabling Votifier v2.7.2
30.06 11:35:32 [Server] INFO [Votifier] Votifier disabled.
30.06 11:35:32 [Server] WARN [com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop.
30.06 11:35:32 [Server] INFO java.lang.IllegalStateException: zip file closed
30.06 11:35:32 [Server] INFO at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:?]
30.06 11:35:32 [Server] INFO at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:?]
30.06 11:35:32 [Server] INFO at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:?]
30.06 11:35:32 [Server] INFO at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:?]
30.06 11:35:32 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.jar:git-Paper-65]
30.06 11:35:32 [Server] INFO at java.lang.ClassLoader.loadClassHelper(Unknown Source) ~[?:?]
30.06 11:35:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
30.06 11:35:32 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.jar:git-Paper-65]
30.06 11:35:32 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-65]
30.06 11:35:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
30.06 11:35:32 [Server] INFO at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2$1.<init>(IntObjectHashMap.java:225) ~[?:?]
30.06 11:35:33 [Multicraft] Server shut down (stopping)
30.06 11:35:33 [Multicraft] Server stopped
```

### Details

**Description**  

As soon as I shut down my server / stop my server, this error is pushed to the console.

**Steps to reproduce**  

I closed down / turned off my server.

**Expected behavior**  

No errors in the console.

**Comment by astei** [comment]
This issue cannot be fully fixed without a lot of effort and the error is not fatal (unless you reload, but we don't support reloading).

**Comment by Waterman1001** [comment]
Oh...
I still hoped it would have been worth the effort.
But thanks for your reply.
