### ISSUE TITLE
Exception in thread "Votifier epoll worker" java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by DeividasAr** [NuVotifier/NuVotifier#269]
[21:24:18 WARN]: Exception in thread "Votifier epoll worker" java.lang.IllegalStateException: zip file closed
[21:24:18 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:829)
[21:24:18 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:328)
[21:24:18 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:519)
[21:24:18 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:474)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[21:24:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[21:24:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:24:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:24:18 WARN]: Exception in thread "Votifier epoll worker" java.lang.IllegalStateException: zip file closed
[21:24:18 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:829)
[21:24:18 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:328)
[21:24:18 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:519)
[21:24:18 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:474)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[21:24:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[21:24:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:24:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:24:18 WARN]: Exception in thread "Votifier epoll boss" java.lang.IllegalStateException: zip file closed
[21:24:18 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:829)
[21:24:18 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:328)
[21:24:18 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:519)
[21:24:18 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:474)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[21:24:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[21:24:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:24:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:24:18 WARN]: Exception in thread "Votifier epoll worker" java.lang.IllegalStateException: zip file closed
[21:24:18 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:829)
[21:24:18 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:328)
[21:24:18 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:519)
[21:24:18 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:474)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[21:24:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[21:24:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[21:24:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:24:18 WARN]:        at nuvotifier-2.7.1.jar//com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

Any ideas what could be the problem here? this happens when i try to start the server but it just shuts down...

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#why-do-i-get-javalangillegalstateexception-zip-file-closed-when-i-shutdown-the-server
