### ISSUE TITLE
NuVotifier Shutdown Issue

### ISSUE THREAD

**Issue by MineagePvP** [NuVotifier/NuVotifier#270]
The server is using spigot 1.8.8 and i get this error when i stop the server and currently using the latest nuvotifier from spigot

[00:09:30 WARN]: Exception in thread "Votifier NIO worker" 
[00:09:30 WARN]: java.util.ConcurrentModificationException
[00:09:30 WARN]: 	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
[00:09:30 WARN]: 	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
[00:09:30 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189)
[00:09:30 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98)
[00:09:30 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[00:09:30 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[00:09:30 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[00:09:30 WARN]: 	at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
[00:09:30 WARN]: 	at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
[00:09:30 WARN]: 	at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
[00:09:30 WARN]: 	at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
[00:09:30 WARN]: 	at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
[00:09:30 WARN]: 	at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:09:30 WARN]: 	at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[00:09:30 WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#why-do-i-get-javalangillegalstateexception-zip-file-closed-when-i-shutdown-the-server
