### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Raesak** [NuVotifier/NuVotifier#283]
Minecraft: 1.17.1
Paper: 388
NuVotifier: #40

Unfortunately I have no context for this error. I've only seen it once:

[11:23:21 ERROR]: [com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.rejectedExecution] Failed to submit a listener notification task. Event loop shut down?
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[patched_1.17.1.jar:git-Paper-388]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-388]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:220) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:208) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[nuvotifier.jar:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#why-do-i-get-javalangillegalstateexception-zip-file-closed-when-i-shutdown-the-server
