### ISSUE TITLE
1.18.1 Console Error

### ISSUE THREAD

**Issue by CyberSiren** [NuVotifier/NuVotifier#284]
`[Votifier]: Enabling Votifier v2.7.3
[Votifier]: Loaded token for website: default
Console18:27:49
at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[nuvotifier.jar:?]
at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[nuvotifier.jar:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by CyberSiren** [comment]
Error appears and nuvotifier seems to not be functioning

**Comment by Ichbinjoe** [comment]
This doesn't contain all logs and is missing other information in the template.

**Comment by CyberSiren** [comment]
Can you tell me where the template is so I can resubmit this bug? I didn't realize there were formatting standards for bug reporting. I was just posting the only errors related to nuvotifier in my log.
