### ISSUE TITLE
New Loading Error

### ISSUE THREAD

**Issue by TheMattVid** [NuVotifier/NuVotifier#3]
02:02:37 [WARNING] Exception encountered when loading plugin: NuVotifier
com.vexsoftware.votifier.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at com.vexsoftware.votifier.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at com.vexsoftware.votifier.json.JSONObject.<init>(JSONObject.java:194)
	at com.vexsoftware.votifier.json.JSONObject.<init>(JSONObject.java:321)
	at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.load(FileVoteCache.java:48)
	at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.<init>(FileVoteCache.java:31)
	at com.vexsoftware.votifier.bungee.NuVotifier.onEnable(NuVotifier.java:251)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:220)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Ichbinjoe** [comment]
Seems like a cache file corruption. Mind pasting your vote cache to pastebin?

**Comment by TheMattVid** [comment]
It's a file called cached-votes.json and it has nothing in it. It's 0 bytes. There are a bunch of votes that failed to process from when I used the last version, but they do not appear in this file.

**Comment by minecrafter** [comment]
Delete the file, and you should be set.

**Comment by TheMattVid** [comment]
No errors on startup, so it seems to have worked

**Comment by TheMattVid** [comment]
Vote processed, everything seems functional. Thanks!
