### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ProtoGhost** [NuVotifier/NuVotifier#306]
[16:25:12 ERROR]: [Votifier] Unable to process vote from /51.195.61.197:52372
com.vexsoftware.votifier.io.netty.handler.codec.CorruptedFrameException: Username too long
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol2Decoder.decode(VotifierProtocol2Decoder.java:65) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol2Decoder.decode(VotifierProtocol2Decoder.java:23) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[nuvotifier.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by JosTheDude** [comment]
What is the username that is trying to vote?

**Comment by JosTheDude** [comment]
Also do a test vote by either `/testvote` or `/ptestvote` and respond with the error if one pops up.
