### ISSUE TITLE
Connection Reset spam?

### ISSUE THREAD

**Issue by MayhemBill** [NuVotifier/NuVotifier#317]
### Information
PaperMC

**Version of NuVotifier**: 

```
2.7.3
```

**Relevant log**: 
```
[21:24:34 ERROR]: [Votifier] Unable to process vote from /159.69.51.125:52106
java.net.SocketException: Connection reset
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at com.vexsoftware.votifier.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[nuvotifier.jar:?]
        at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[nuvotifier.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
**Description**  
So I get the issue above seemingly randomly in the console, and it has happened a lot lately, it's almost random IPs, but they're all from Hetzner owned locations. I believe it is some type of spam?

Steps to reproduce:
install and setup NuVotifier, then wait, eventually it'll start coming in randomly.

No one is online, as far as I can tell no one has voted on any platform.

**Comment by tomlyo** [comment]
Our server experienced the same error today, and confirmed nobody voted. The IP appears to be from a random Linode VPS in our case.

**Comment by AGuyNamedJens** [comment]
To add on this, seen this issue in my server for years now, seems to be the Scanning botnets that target ips to try and login to them/scan them for server raid lists..
