### ISSUE TITLE
TooLongFrameException

### ISSUE THREAD

**Issue by Poofit** [NuVotifier/NuVotifier#319]
I'm getting an error when trying to implement the nuvotifier protocal in c#.

> `com.vexsoftware.votifier.io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 1024: 31526 - discarded
>         at com.vexsoftware.votifier.io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:503) ~[nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:489) ~[nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:376) ~[nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:419) ~[nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:332) ~[nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [nuvotifier%20(3).jar:?]
>         at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [nuvotifier%20(3).jar:?]
>         at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352-352]`

I have tried using other sites to test without my code and I'm still getting the issue.
https://minestatus.net/tools/votifier

V1 appears to be fine but V2 doesn't work. I get the error above.

I've tried using the PHP example given and that also has the same issue.

Spigot version: 
spigot-1.14.4

NuVotifier version:
2.7.3

Steps to reproduce:
1. Setup up votifier
2. Go to mcstatus (link above) and send a test vote
3. See error in console

**Comment by astei** [comment]
There are known working v2 clients in [PHP](https://github.com/NuVotifier/votifier2-php), [Go](https://github.com/NuVotifier/go-votifier), and [Node.js](https://github.com/NuVotifier/votifier2-js) you could have based your code off.

Admittedly it's been a while since these have been updated, try another library (the Go and Node.js ones I know will work).
