### ISSUE TITLE
NuVotifier Decryption Error with v2 Protocol Behind HAProxy

### ISSUE THREAD

**Issue by Mattrolol** [NuVotifier/NuVotifier#337]
### Information

**Platform on which you run NuVotifier**: BungeeCord Build #1862

**Version of NuVotifier**: v2.7.3

**Relevant log**:
```
00:37:08 [SEVERE] [NuVotifier] Unable to process vote from /100.94.191.28:38274
com.vexsoftware.votifier.io.netty.handler.codec.DecoderException: com.vexsoftware.votifier.util.QuietException: Could not decrypt data from /100.94.191.28:38274 as it is too long. Attack?
    at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
    at com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at com.vexsoftware.votifier.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at com.vexsoftware.votifier.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
    at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
    at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.vexsoftware.votifier.util.QuietException: Could not decrypt data from /100.94.191.28:38274 as it is too long. Attack?
```

### Details

**Description**  
I’m encountering an issue with NuVotifier when it’s behind a proxy (HAProxy). Votes are not processed correctly due to a decryption error. The issue seems to be related to the use of the v2 protocol, which NuVotifier does not fully support. As a workaround, I switched to the v1 protocol, which allows votes to be processed correctly. However, this configuration reveals the HAProxy server's IP instead of the original client's IP. This issue may be related to [issue #315](https://github.com/NuVotifier/NuVotifier/issues/315) on the NuVotifier GitHub repository.

**Steps to reproduce**  
1. Configure NuVotifier behind HAProxy with v2 protocol.
2. Attempt to process votes.
3. Observe the decryption error.

**Expected behavior**  
Votes should be processed correctly, and the original client’s IP should be preserved rather than showing the HAProxy server’s IP.

**Comment by KrispyBigPvp** [comment]
have you found a fix by any chance? im using playit.gg and this issue happens to me as well

**Comment by Mattrolol** [comment]
Yeah, I’ve made a change that should support HAProxy v1 and v2. You can check it out here: GitHub - [Mattrolol/NuVotifier](https://github.com/Mattrolol/NuVotifier). Let me know if you run into any issues! 🚀

**Comment by Mattrolol** [comment]
@HawksBoy12
You deleted your message, but I'll just send this anyway—I've compiled and built the [Experimental Build](https://github.com/Mattrolol/NuVotifier/releases/tag/Experimental) for you. Let me know if you need any help!
