### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by ThibautDT** [NuVotifier/NuVotifier#45]
i got this error in bungee console (debug mode: true)

java.lang.IllegalArgumentException: port out of range:-25522
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:188)
	at com.vexsoftware.votifier.bungee.NuVotifier.onEnable(NuVotifier.java:309)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Voting forwarding isn't working
what is wrong with it? and what can i do to fix it?

**Comment by Ichbinjoe** [comment]
You specified a negative port for your listener. Ports go from 1 - 65535.

**Comment by ThibautDT** [comment]
nope i didn't that's the thing

**Comment by Ichbinjoe** [comment]
This is a configuration issue. There is no way the plugin would ever choose this port unless you were to configure it that way. Feel free to upload your config.

**Comment by ThibautDT** [comment]
can u contact me on discord plz? ThibautDT#3073

**Comment by Ichbinjoe** [comment]
no. upload your configuration or I cannot help you.

**Comment by ThibautDT** [comment]
[https://pastebin.com/KMV5jhhb](url)

here it is
