### ISSUE TITLE
Problem using NuVotifier

### ISSUE THREAD

**Issue by xBoneso** [NuVotifier/NuVotifier#51]
Hello, I am using NuVotifier 2.3.5,

And I keep getting this problem:
[22:04:48 ERROR]: [Votifier] Votifier was not able to bind to /0.0.0.0:40866
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_112]
        at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_112]
        at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_112]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_112]
        at com.vexsoftware.votifier.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128) ~[nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannel.bind(AbstractChannel.java:254) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [nuvotifier-universal-2.3.6-pre.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [nuvotifier-universal-2.3.6-pre.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

And sometimes it says Port is already being used

Although none of them is being used....

**Comment by Ichbinjoe** [comment]
As the error states, there is already something listening on this port. NuVotifier requires a unique port so it can bind the Votifier server to it.

If you are on a shared host, please consult your hosting provider.
If you are on a dedicated host, you can see what is taking the port by running this command as root in shell (assuming you are on Linux):

```
netstat -tulp | grep :40866
```
