### ISSUE TITLE
Votes throwing major error [not registering] {HIGHEST PRIORITY}

### ISSUE THREAD

**Issue by GameHoundInteractive** [NuVotifier/NuVotifier#64]
Error:
 [13:08:32 INFO]: [Votifier] Got a forwarded vote -> Vote (from:Minecraft-MP.com username:DuckCraftPvP address:99.241.98.127 timeStamp:1519063713)
[13:08:32 WARN]: [Votifier] Task #290501 for Votifier v2.3.3 generated an exception
java.lang.LinkageError: loader constraint violation: when resolving method "com.vexsoftware.votifier.model.VotifierEvent.<init>(Lcom/vexsoftware/votifier/model/Vote;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/vexsoftware/votifier/NuVotifierBukkit$4, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/vexsoftware/votifier/model/VotifierEvent, have different Class objects for the type com/vexsoftware/votifier/model/Vote used in the signature
	at com.vexsoftware.votifier.NuVotifierBukkit$4.run(NuVotifierBukkit.java:378) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by Ichbinjoe** [comment]
What plugins do you have installed? Do you perhaps have the original votifier installed as well?

**Comment by GameHoundInteractive** [comment]
I have not ever even tried the original votifier.

**Comment by Ichbinjoe** [comment]
Did you restart the server to add the plugin, or did you use some reload mechanic

**Comment by GameHoundInteractive** [comment]
i used plugman. il try rebooting then let you know.

**Comment by GameHoundInteractive** [comment]
it works now, :/ plugman should work on all plugins.

**Comment by Ichbinjoe** [comment]
Plugman and other reloading mechanics are known to be fragile, and generally not to be trusted due to Bukkits classloader implementation.
