### ISSUE TITLE
enableExternal: false is broken

### ISSUE THREAD

**Issue by L4BORG** [NuVotifier/NuVotifier#65]
```[11:02:40 ERROR]: [Votifier] Votifier was not able to bind to /127.0.0.1:8192
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_152]
        at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_152]
        at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_152]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_152]
        at com.vexsoftware.votifier.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128) ~[nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannel.bind(AbstractChannel.java:254) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [nuvotifier-universal.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [nuvotifier-universal.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

config

```
# The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
# This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: 127.0.0.1

# Port to listen for new votes on
port: 8192

# Whether or not to print debug messages. In a production system, this should be set to false.
# This is useful when initially setting up NuVotifier to ensure votes are being delivered.
debug: false

# Setting this value to false will turn off the votifier port listening for external votes. This is beneficial if the server
# is only listening for votes coming from NuVotifier running on your BungeeCord.
enableExternal: false

# Setting this option to true will disable handling of Protocol v1 packets. While the old protocol is not secure, this
# option is currently not recommended as most voting sites only support the old protocol at present. However, if you are
# using NuVotifier's proxy forwarding mechanism, enabling this option will increase your server's security.
disable-v1-protocol: true

# All tokens, labeled by the serviceName of each server list.
tokens:
  # Default token for all server lists, if another isn't supplied.
  default: ....

# Configuration section for all vote forwarding to NuVotifier
forwarding:
  # Sets whether to set up a remote method for fowarding. Supported methods:
  # - none - Does not set up a forwarding method.
  # - pluginMessaging - Sets up plugin messaging
  method: pluginMessaging
  pluginMessaging:
    channel: NuVotifier
```

using latest build from spigotmc

**Comment by L4BORG** [comment]
As result spigot and bungee instance are now listening or tryint to listen on port 8192

**Comment by L4BORG** [comment]
And https://github.com/NuVotifier/NuVotifier/issues/49 is not really solution as binding to random port could cause even more issues (technical and security)

**Comment by L4BORG** [comment]
If anything it would be better to remove whole listening part from bukkit plugin

**Comment by L4BORG** [comment]
Or even better not listen if port is set to 0

**Comment by Ichbinjoe** [comment]
enableExternal was removed by Tux some time ago because it confused people. While both of us do agree that enable xternal is better for a multitude of reasons, the issue is simply that most server admins (if they can really be called that... let’s call them kids with ftp) didn’t understand the option, and as a result the amount of support was vastly weighted to supporting enableExternal.

I think the right solution is to instead add a special case where the port is set to -1... 0, while non-sensical, has a special usage in OS land. For the immediate time being, you can set your port to something random (52932 maybe?), and locally bind it so that nothing outside your box. I think having a special port value will be better than having enable external be a configuration (since it would prevent non-technical ‘ftp’ users from messing with this)

**Comment by Ichbinjoe** [comment]
Implemented in next release
