### ISSUE TITLE
Sometimes the vote doesn't work

### ISSUE THREAD

**Issue by TrademarkTM** [NuVotifier/NuVotifier#67]
Hey!
I'm getting this error pretty frequently:
```
[17:11:05] [nioEventLoopGroup-2-1/ERROR]: [Votifier] Unable to process vote from /149.202.74.183:33116
java.io.IOException: Conexão fechada pela outra ponta # Connection closed
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at com.vexsoftware.votifier.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [nuVotifier%202.3.6.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [nuVotifier%202.3.6.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
The vote is from Minecraft-MP (very likely to happen). From TopG it is quite unusual.

It sometimes happens, sometimes doesn't. I lose about 50% of the votings because of it. Any fixes or workarounds?

**Comment by Ichbinjoe** [comment]
Is this you testing which is deriving these results, or just observed results?

Looks a lot like #27... lets track the issue there instead. Please answer whether or not you get the received vote immediately preceding this error - if so, we can add logic to supress the error as we WERE actually able to process the vote, and if not, we may not be able to do anything anyways since Minecraft-MP closed the vote socket before we were even able to process the vote...
